# Basic
title: Casie Bao
subtitle: 

description: All the lights we cannot see

# creator: <a href="http:/hellolzc.github.io">@hellolzc</a>
url: "https://kcbao.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 8
paginate_path: "page/:num/"

# Social
social:
    # weibo: onevcat
    github: KCbao
    # twitter: onevcat
    # mail:
    linkedin: anyi-casie-bao-78186aa7

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# page.excerpt truncate characters
truncate_num: 200
